
DROP DATABASE IF EXISTS Employee_Tracker_DB;

CREATE DATABASE Employee_Tracker_DB;

USE Employee_Tracker_DB;

CREATE TABLE DEPARTMENT (
  department_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  employee_name VARCHAR(100) NOT NULL,
  salary DECIMAL NULL,
  quantity INT NULL,
  PRIMARY KEY (id)
);


CREATE TABLE ROLES (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  quantity INT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE Employee_List (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
    hours_worked_per_day DECIMAL(10,2) NULL,
  PRIMARY KEY (id)
);